### ISSUE TITLE
Why project argument has to come with -P?

### ISSUE THREAD

**Issue by navidcy** [coecms/nci_scripts#10]
https://github.com/coecms/nci_scripts/blob/8b98a8cf6db37a8ae2f40b4b7acd779a210baba8/gadi_jupyter#L31

Isn't it a bit counterintuitive? I was confused at the beginning and I think @edoddridge also got it wrong at the start.

@ScottWales, is there a reason for this?

**Comment by ScottWales** [comment]
It's intended to be an internal variable, left unmodified in the script, with normal practice being you run `./gadi_jupyter` without `-P` to use your default project, and with `-P ab12` if you want to run on e.g. `ab12`. It's just simpler in the code to add the -P when parsing the command line arguments.

Since this is causing issues for people I'll add some variable expansion magic so the -P can be excluded.
